#ifndef _MCU_ERRORS_H
#define _MCU_ERRORS_H

#include <3ds/result.h>

// module specific mcu

// module specific os

#define OS_REMOTE_SESSION_CLOSED         MAKERESULT(RL_STATUS   , RS_CANCELED, RM_OS, 26) // C920181A
#define OS_INVALID_IPC_ARGUMENT          MAKERESULT(RL_PERMANENT, RS_WRONGARG, RM_OS, 48) // D9001830
#define OS_INVALID_IPC_HEADER            MAKERESULT(RL_PERMANENT, RS_WRONGARG, RM_OS, 47) // D900182F
#define OS_EXCEEDED_HANDLES_INDEX        MAKERESULT(RL_PERMANENT, RS_WRONGARG, RM_OS, 49) // D9001831

// general mcu
#define MCU_INTERNAL_RANGE               MAKERESULT(RL_FATAL, RS_INTERNAL  , RM_MCU, RD_OUT_OF_RANGE)
#define MCU_INVALID_SIZE                 MAKERESULT(RL_USAGE, RS_INVALIDARG, RM_MCU, RD_INVALID_SIZE)

// general os

#define OS_MISALIGNED_ADDRESS            MAKERESULT(RL_USAGE, RS_INVALIDARG, RM_OS, RD_MISALIGNED_ADDRESS)

// ACCelerometer

#define ACC_FAILURE                      MAKERESULT(RL_USAGE    , RS_INVALIDARG, RM_ACC, 1)
#define ACC_BAD_INPUT_SCALE              MAKERESULT(RL_USAGE    , RS_WRONGARG  , RM_ACC, 2)
#define ACC_BAD_SCALE                    MAKERESULT(RL_TEMPORARY, RS_INTERNAL  , RM_ACC, 2)

#define ACC_BAD_REG_ID                   MAKERESULT(RL_USAGE, RS_INVALIDARG, RM_ACC, RD_INVALID_ADDRESS)

#endif